# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movie app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	
		 pod 'AFNetworking', '~> 3.0'
   pod ‘JSONModel’
	pod ‘SDWebImage’,’~>4.0’
	pod ‘HCSStarRatingView’
  # Pods for movie app

  target 'movie appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'movie appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
